.PHONY: clean All

All:
	@echo "----------Building project:[ Heightmap - Debug ]----------"
	@"$(MAKE)" -f  "Heightmap.mk"
clean:
	@echo "----------Cleaning project:[ Heightmap - Debug ]----------"
	@"$(MAKE)" -f  "Heightmap.mk" clean
